/**
 * GENERATED by scripts/films.mjs — do not edit.
 *
 * One record per campaign film: the segment's length, its intrinsic size, an
 * alt string written against what is in the picture, and a blur placeholder
 * taken from the poster frame.
 */

export type Film = {
  slug: string;
  alt: string;
  width: number;
  height: number;
  /** Trimmed length, used to stagger the panes so they do not loop in unison. */
  seconds: number;
  blur: string;
};

export const FILMS: Record<string, Film> = {
  "film-sash": {
    "slug": "film-sash",
    "alt": "A model in a cream shirt with a navy sash and denim-trimmed collar, in a plaster courtyard.",
    "width": 720,
    "height": 1280,
    "seconds": 5,
    "blur": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAADQBgCdASoUACQAPt1cqE8opKOiKrgMARAbiUAWdnSgi4loYtTPKM1DMZAaedEFgXcqpf9R6aYUkHxXLxvB8gAA/tOE1bu57it25KiB/lKxFA1hrf5x3hxoi0m5h6dOMbaUTRp/qNiDGUPXBKzfcVRZ6p8gD0/3EdNzJEHNYXtBTaolRRYkG4SnC09tH27ZZZ4UkBmbCnFsOjdhlJN6fgnJ3DVF5XOGSjeviwu7+lZWYxOH79naihRBGkvbhbAotq00hzmmnC0gpAAA"
  },
  "film-coral": {
    "slug": "film-coral",
    "alt": "A model in a black pinstripe shirt embroidered with a spray of coral-pink flowers, against a carved stone wall.",
    "width": 720,
    "height": 1280,
    "seconds": 5.1,
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAAAwBgCdASoUACQAPt1ipk6opaMiKqoBEBuJQBbfbRgrLwJ7jyIGM1rUZM5HMYLPBSaHgF0dT2fnizQAAP6e6xUfdYZwza+QpsvdHjK67y2N1+Q/pdo2boWyDYToFk7iLHFA7PJqcFMhmkhYo1hQ1nrAnc7LnJRVQg7QiXEPRRDvR6XxxRdDw1F0td3+jpRhlAuYflXGeCEPgVEisqLNcGLDpJ8ge4LtUl/6sPqsoKadXpNHlGBN7VHL8iwAAA=="
  },
  "film-column": {
    "slug": "film-column",
    "alt": "A model in a lilac satin column gown, then in a deep burgundy gown worked with velvet flowers.",
    "width": 720,
    "height": 1280,
    "seconds": 5.6,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBQCdASoUACQAPt1cp02opKOiMBqoARAbiWUAz9wWbUAEjOaVEK0rONntPAZEi0WC+5AA/u1B9LLWCHW28RySxzfSoo6cZilNsXTU3lPEu5ULW+UCpJEQ0zOKvtn33mTvHjIY/0KTA+PTc2KLnynSuco0s7tPDg6OHiqDj6M7m8YesGUZTpI0AAA="
  },
  "film-women": {
    "slug": "film-women",
    "alt": "A model in a burgundy gown worked with velvet flowers, then in a grey column gown with a crystal hem.",
    "width": 720,
    "height": 1280,
    "seconds": 7.8,
    "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAABQBgCdASoUACQAPt1gpE4opaMiKqwBEBuJYwC7AywTmofoeJE3mytl5m1GVr+Dn8zmFMAHoG2wbCySwAD+78iIfvNTO3dZDbGEdBXi9J47sVsQZkjFSQzQihY8Swmk4z2dXNSrAOKKx6SUaeahRX1P7Gind/uHK/aDlg6oxIm3M+YkEhUuQaLiCYpEV9DSDqejadSodoSWl8I0Hs+/rbu4jPl9qgFDkceqV02Puj7EW6JUYNqI8CeNxCRw1mlKJ2suf3+LF4nLC73k0/KDhIf4AAA="
  },
  "film-men": {
    "slug": "film-men",
    "alt": "A model in a midnight dinner jacket embroidered with swirls of crystal, seated on a studio stool.",
    "width": 720,
    "height": 1280,
    "seconds": 6.1,
    "blur": "data:image/webp;base64,UklGRgABAABXRUJQVlA4IPQAAAAQBgCdASoUACQAPt1apUyopSOiKq35EBuJZQDM0YxEmIqcM/g90q/uh7MR+fy1cRIGwVo2cOghMcAA/u/UaACGxP/ApX5m6fK8vYfn5M5/4ciQ6wNstDy/CU4BWMyFkYy24RAqX3Ucfk60HAUzxECoXEk0WFI8mOsC37DNC24cZUvE1j6ZkR67nAVrKfwaa7/CYauGEEVz0Oio7gX8FZPS2/3/t7FyqxlaFwPY2oCzamMvSwfWq7BTUVaTDGNmhX28wid+2M/9l9Up+h4dC70/xPSXH2dPT08UcMF2bODIrmpKYLP6Iip3ROgiy7ut9LW3KuAA"
  },
  "film-occasion": {
    "slug": "film-occasion",
    "alt": "Hand-set black and red spiral embroidery on the collar of a white shirt, worn against a carved stone wall.",
    "width": 720,
    "height": 1280,
    "seconds": 5.7,
    "blur": "data:image/webp;base64,UklGRhABAABXRUJQVlA4IAQBAABQBgCdASoUACQAPt1srlIopaQipWgBEBuJQBhmsXnCdE+P/6UPq7jJ5S/1Db0OTTsdSWSZ39hVcZtryAD+9NNyr8dAKta8J3VJAate1ZHfnDIqWmbpoT96F779cXNyHI1WTFANfyOQVT6cw1fB43NhDQaoAHSh+4ypFdHBTRCSPxpW0dTUXC9PelNDU2Y0CwKvke6CWYkMOoGk3GGqxgYUMFzmVjTUlGDc/ZK0bjbsWA3RqLhx12UCKTbYRE6cvnLxGhat3Vsu0Nz0tqwNJ5dxiYbcpTBcd6d6Cl4lsiZ31wtdKs0Wj3LHsp9H2JDb1WUEtsWtKO/MLq4LStR+DgsrWsAAAA=="
  }
};

/** One encode. See the note in scripts/films.mjs for why there is no VP9. */
export const filmMp4 = (slug: string) => `/video/${slug}.mp4`;
export const filmPoster = (slug: string) => `/img/film/${slug}.webp`;
export const filmBlur = (slug: string) => FILMS[slug]?.blur;
