/**
 * GENERATED by scripts/films.mjs — do not edit.
 *
 * One record per campaign film: the segment's length, its intrinsic size, an
 * alt string written against what is in the picture, and a blur placeholder
 * taken from the poster frame.
 */

export type Film = {
  slug: string;
  alt: string;
  width: number;
  height: number;
  /** Trimmed length, used to stagger the panes so they do not loop in unison. */
  seconds: number;
  blur: string;
};

export const FILMS: Record<string, Film> = {
  "film-sash": {
    "slug": "film-sash",
    "alt": "A model in a cream shirt with a navy sash and denim-trimmed collar, in a plaster courtyard.",
    "width": 720,
    "height": 1280,
    "seconds": 5,
    "blur": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAADQBgCdASoUACQAPt1cqE8opKOiKrgMARAbiUAWdnSgi4loYtTPKM1DMZAaedEFgXcqpf9R6aYUkHxXLxvB8gAA/tOE1bu57it25KiB/lKxFA1hrf5x3hxoi0m5h6dOMbaUTRp/qNiDGUPXBKzfcVRZ6p8gD0/3EdNzJEHNYXtBTaolRRYkG4SnC09tH27ZZZ4UkBmbCnFsOjdhlJN6fgnJ3DVF5XOGSjeviwu7+lZWYxOH79naihRBGkvbhbAotq00hzmmnC0gpAAA"
  },
  "film-coral": {
    "slug": "film-coral",
    "alt": "A model in a black pinstripe shirt embroidered with a spray of coral-pink flowers, against a carved stone wall.",
    "width": 720,
    "height": 1280,
    "seconds": 5.1,
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAAAwBgCdASoUACQAPt1ipk6opaMiKqoBEBuJQBbfbRgrLwJ7jyIGM1rUZM5HMYLPBSaHgF0dT2fnizQAAP6e6xUfdYZwza+QpsvdHjK67y2N1+Q/pdo2boWyDYToFk7iLHFA7PJqcFMhmkhYo1hQ1nrAnc7LnJRVQg7QiXEPRRDvR6XxxRdDw1F0td3+jpRhlAuYflXGeCEPgVEisqLNcGLDpJ8ge4LtUl/6sPqsoKadXpNHlGBN7VHL8iwAAA=="
  },
  "film-column": {
    "slug": "film-column",
    "alt": "A model in a lilac satin column gown, then in a deep burgundy gown worked with velvet flowers.",
    "width": 720,
    "height": 1280,
    "seconds": 5.6,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBQCdASoUACQAPt1cp02opKOiMBqoARAbiWUAz9wWbUAEjOaVEK0rONntPAZEi0WC+5AA/u1B9LLWCHW28RySxzfSoo6cZilNsXTU3lPEu5ULW+UCpJEQ0zOKvtn33mTvHjIY/0KTA+PTc2KLnynSuco0s7tPDg6OHiqDj6M7m8YesGUZTpI0AAA="
  }
};

/** One encode. See the note in scripts/films.mjs for why there is no VP9. */
export const filmMp4 = (slug: string) => `/video/${slug}.mp4`;
export const filmPoster = (slug: string) => `/img/film/${slug}.webp`;
export const filmBlur = (slug: string) => FILMS[slug]?.blur;
