/**
 * GENERATED by scripts/photos.mjs — do not edit.
 *
 * One record per campaign frame: the intrinsic size (so every <img> can reserve
 * its box and the page never shifts), an alt string written against what is
 * actually in the picture, and a 20px blur placeholder to hold the space in
 * the right colours while the full plate decodes.
 */

export type Photo = {
  slug: string;
  alt: string;
  width: number;
  height: number;
  /** Inlined 20px WebP, scaled up under a blur until the real plate arrives. */
  blur: string;
};

export const PHOTOS: Record<string, Photo> = {
  "noir-vine-01": {
    "slug": "noir-vine-01",
    "alt": "Model in a long navy sherwani with scalloped metallic embroidery at the hem and cuffs.",
    "width": 3935,
    "height": 5247,
    "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABQBACdASoUABsAPt1iqE4opaOyMBgIAkAbiWUAx+QQptC0ZD6wupxz47awAP7vw7aP4AALFvIc/gz3VIkt9SuYNpjGNktLASHCPVNf2BNVFnkMymKjsTDCt9NdhHgCjfRdhLBar78TlXRxne+5ddYNCyr+mKYxCrqvFMccPLhe9gB9vH+1vkqrW382Ey6JMEdKVnPgdWr/TwTCyGgAAA=="
  },
  "noir-vine-02": {
    "slug": "noir-vine-02",
    "alt": "Close detail of the scalloped metallic hem and cuff on a navy sherwani.",
    "width": 3663,
    "height": 4885,
    "blur": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAABwBQCdASoUABsAPt1aqE6opKOiMBgIARAbiUAW2WWAGuDDS5zRtxwJA2Z4Fosjl2WSMPCAAP7SsrA61gJklE5eWxqdbXodfuHHUIzPDvc4RX1L7qpr+pxaR9+IGUCq59X1Pz5RT2w+4vrmn8fW3/6pH+ZZIMv6f0o8dVOoszi0HH8Usif9HddfsRvZ7QvKjozuKDMsiZEdSlKifgmwAsMZCk8JJ5C0G4mOoEmhTEN8L41O9uN9bj/1zTu9zDuS3//cHl75S9OGRATQg5hQNLnH1LT6lDwAAAA="
  },
  "nocturne-gown-01": {
    "slug": "nocturne-gown-01",
    "alt": "Model in a navy strapless corset top and draped column skirt, a line of crystal across the bodice.",
    "width": 3945,
    "height": 5260,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBACdASoUABsAPt1kqE2opaOiMBgIARAbiWcAzfwMZ/ft9/AYnBZmEg42AAD+79dGzUUyr1w0kE4GtQXDRF4r6QffL+T8nC1cXqoRpDkscmT55IoQQGAdgC+GVShjvUWZdnMPhJhz85r5jeEP5XEmpccvuXcE2nGEl9qjW22M2yjAHnoegTXyhAA="
  },
  "nocturne-gown-02": {
    "slug": "nocturne-gown-02",
    "alt": "Navy pleated strapless top with a diagonal crystal line, worn over a draped skirt.",
    "width": 3469,
    "height": 4625,
    "blur": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAQBQCdASoUABsAPt1mqlEopSOiqAgBEBuJQBYj7IAxUaNTeLUj8WWosw9/IW3vEE7AAP7qtT+Tydjlk1gpbVNszkh0nE7RH0L7K7CdhS1qOnDE+pWacv03GT5Tglkj8X7T/V3F2SovIel+3SfwfHq65n7Q0YYaALvgtTyftofW+CLTM5VRZJ1CnR/pvj4BJFmgrFnM7Sseszul00v1JcBtdFD3J8MCKYjcbiJp6AAAAA=="
  },
  "nocturne-gown-03": {
    "slug": "nocturne-gown-03",
    "alt": "Model in a navy pleated strapless top with crystal trim.",
    "width": 3533,
    "height": 4711,
    "blur": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAADwBQCdASoUABsAPt1eqE0opSQiKA1REBuJYgCdMuI1O0kUzGe112nRY+nsGOk+abohLy4KD1FEVAD+79cVTcwkE2bQ40a/4oD12aalTHpBcsrqo4YA7K7OdybJbgjaeqp5NolONqkv0VPRm1G+aGSQEXSrzyFJ+NXoyyAxqSSB2PIY3qHdA4aIr6i3RKavvD8UHUVe16yKAMhdCfa25VOScIIN4VlHyV7yAnuwg8ai1ENWmUJ3eLG39LD5L67ItI5G9katwG9MaU/0TL7u4fWPZ56sNIqhBAA="
  },
  "nocturne-gown-04": {
    "slug": "nocturne-gown-04",
    "alt": "Model in a white pinstripe shirt with a navy claw-mark embroidery at the chest.",
    "width": 3680,
    "height": 4906,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBACdASoUABsAPt1kqE2opiOiMBgIARAbiWkA0JARfNc5Uk5YUOIc+QQAQAD+8dxN+kGS8hPnrLeOpJMOvljJScuwyMyRNKzMGNpyYUprzE+lLbsHegThFWKWu9oQ+Wz9iPVMjikQ7vpuzCvI+kV1WWo1VYPqS5kAAA=="
  },
  "silver-seam-01": {
    "slug": "silver-seam-01",
    "alt": "Model in a black zip jacket hand-painted with white brushstrokes.",
    "width": 3806,
    "height": 5074,
    "blur": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAADwBACdASoUABsAPt1irE8opaSiKAqpEBuJZQDM0YwSa3OCDfyqW4rHsMEGl+0DAAAA/u/M32bQeJMV2jFQJag7L7jccAPXDCtpY+Q0YroD21wKQ08L6PUiv6+e8grK1MIzAIqKFOTFE2zmfzCb54zWCiWa5XCyA50vJdITkRRIV3UHMt7V3A7hSOpLsFJ5DiUEdIKEazys1IpJshOI981xTO+7uS7ivZjRYFGG08DPvj4ou53Izy0AAAA="
  },
  "silver-seam-02": {
    "slug": "silver-seam-02",
    "alt": "Full-length model in a black hand-painted zip jacket and black trousers.",
    "width": 3723,
    "height": 4964,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoUABsAPt1ip02opaOsMBgIAYAbiWcAACqwMOPbKNdnZb/jwXgA/u/XTTpfujGVCavtN2Cvz21fqR+quGtWkqFGJdAcjIYYDMza9g5r0EWZ8SQXW236rWpq6a4Al0nosrwWFrdd3+CHFFEtPRQKUcTyWpYMWsBUpw2EK8yfksPbS9N87nOqSivrECPhpXR9Zj+a0/qNnvdL3lWUXV4AAA=="
  },
  "silver-seam-detail": {
    "slug": "silver-seam-detail",
    "alt": "Close detail of white brushstroke painting and a pleated collar on a black zip jacket.",
    "width": 3224,
    "height": 4299,
    "blur": "data:image/webp;base64,UklGRgoBAABXRUJQVlA4IP4AAABQBQCdASoUABsAPt1kqU+opaOiKAqpEBuJZQDGfYu4XmZlXxBn3Njq4Qbry3bzpUm5zgAA/cIVCYSCZloqtqOaaMlc/ICOMaKtOE7LKON12axpYpdxvV7DwVGEDFiyoOAetVkPTJi+RVkeI9hUOdchvZntPkt7iv1+SuY+nh6k1TV1NfvGW1UzR7cmjtKrypvA4nL1jwWoV4dXzOSyUmLIVvMogbrCFdh5l0DsPSiT5jQ3GF9QGUqRJUZDueBJWHnrO+0MLdD/ZsMhodbXSGF4tCme54ITnJ+GG+Y+97QDM3AJKnVMdyLeuzKcZbKw8Rdu4L3E6MK6mL4MNkAAAA=="
  },
  "orbit-01": {
    "slug": "orbit-01",
    "alt": "Model in a black shirt with a woven black-and-white checkerboard panel.",
    "width": 3608,
    "height": 4811,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACwBACdASoUABsAPt1eo0yopSMiMBgMARAbiWUAA+YY1hAyIMUg8boAyfPRhvAAAP7x188MW2HOgsw6dT1AZ7EKwIJJ8GdU36V7CYDUn0xIwBoP5v5R6rQYuoNl+lf0b3wf3zyu/7wJ/M/Vj5evkcBtEqtxR2IM8qkc4HXnLMC7UPC0PYyWTU/XiV762AwOr02o6g3WMslwK8MfCAA="
  },
  "orbit-02": {
    "slug": "orbit-02",
    "alt": "Model leaning against a wall in a black checkerboard-panel shirt.",
    "width": 3848,
    "height": 5131,
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAACwBQCdASoUABsAPt1gp04opaMiMBgIARAbiWUAznWL1mVuttQDiRzfZFIsDzddIbnIdJiueFAA/vHgZv1HI0wPNesKi9OdNJ9W+1Fpawn3z2iJu2v5u0lyKyl28UR2iIcv83c41NHjYNuZuxdD/NjoqZqgbpPPD/YLzF2s7E8Wx5z7scBMz8DwdBZmllgcPU1ym++4JdPXYmjF5HL0pxg6KylLoc9XVfT6Ouje/2af9QRaGH+L78hgaxiuxDEaIA5cqLKs7mjloc8gAAA="
  },
  "orbit-03": {
    "slug": "orbit-03",
    "alt": "Model looking back over his shoulder in a white pinstripe shirt with a tiger embroidered on the back.",
    "width": 3901,
    "height": 5201,
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoUABsAPt1ep0yopSOiMAgBEBuJZwDMWCLWuz6crK35E1TCb9eAAP7vzMpbxbERaKE/7x/I4aTOf+zVhx+CTZkvXwbFxak9XTJ1BaTkopNECAy/YF1KgW4sOQevOuAOGxIKNVM6OCTZ6EWwrK/M6hGfDQTO9ScMO3D/JryHC+QAAA=="
  },
  "vapour-gown-01": {
    "slug": "vapour-gown-01",
    "alt": "Model in a lilac satin slip gown with crystal scattered from the waist and a sequinned hem.",
    "width": 3693,
    "height": 4924,
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoUABsAPt1cpkyopSOiMAgBEBuJZwAAWk+Uvx0oKSqC5GqAAP7qezttPekA8XyWI50+2Yu3fYQB4oQYqifPzqjlXkKF/g6qIyriyEGKaUV1cWCOJYvAhgaTey/Dc9Amv9uB4AAA"
  },
  "vapour-gown-detail": {
    "slug": "vapour-gown-detail",
    "alt": "Lilac satin slip gown with crystals scattered across the bodice.",
    "width": 3680,
    "height": 4906,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABwBQCdASoUABsAPt1cqU6opKOiMBgIARAbiWMAtukPgURn4dTo8BpSEu5s+ZMmyimYAojQAP7qf7xdp9eTj910IDrJM7AC5MyKGAZ7C3u61Bzg6aNtJWJrHo1dYC7JamnV+Li8DSeZwHwAaJEdDMMMNuZr2mUjZJHY52ZqpyPioj6NNclwx20LVdLXqVuQkRQIrP0W0LmQXpL2RDmY/diTAJYFOYKdpld7oSOQdR4KjmV4wAzgAA=="
  },
  "midnight-swirl-01": {
    "slug": "midnight-swirl-01",
    "alt": "Model in a charcoal shawl-collar dinner jacket with metallic swirl embroidery.",
    "width": 3648,
    "height": 4864,
    "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoUABsAPt1kqk8opaOiKAqpEBuJZwAALdg59eMMz+TdH3j3gAD+7Ug4vy7JjAS8ZudLNMNnWn9ux3z/ffUeXpH14dvb/UrD1NMG/a9ohDvOgn1Du7xS77ghElb85u7HBWDNk4mioKO4Ou1ZNCcMUF5lLvC0ac8BuWdHK+9ouhUWmsZgUwAAAA=="
  },
  "midnight-swirl-detail": {
    "slug": "midnight-swirl-detail",
    "alt": "Close detail of metallic swirl embroidery on a charcoal dinner jacket.",
    "width": 3561,
    "height": 4748,
    "blur": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAADQBQCdASoUABsAPt1irE8opaSiKAqpEBuJZQDLaY0Mc+mKMJgOu8P/6DDF/ZEnGVfH3/2A1IIAAP7vxqI6cuTLYu8q8pJFX/7qrr/ZocwTjVFokddjPzXya0jOhn6vk4c6WReRzD9wzWqPGcosSEVDlHchwY5bwoOyOWmpfgtwDN/B/MSceJGQuErNzKescNTHi4fD3qLq1mh5tKJlElHkJGSBk1eYCFpn4W7fNfO+371KUL6ZpCsWJelE/dk4iIyTju1VVPgNwPdd/HtxfmCz8qsRWGImgAA="
  },
  "tidemark-detail": {
    "slug": "tidemark-detail",
    "alt": "Scalloped metallic embroidery along the hem and cuff of a long navy sherwani.",
    "width": 4000,
    "height": 5333,
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAAAwBQCdASoUABsAPt1apEyopSOiMAgBEBuJZQDG9CB0b/9sfpHlvy31pVG/GRiiSazaAAD+79RzWXKAbUAwDna3Ob62tUM4Jh9sPabELdnapYU6O4ZqMim6/6HmH7q06Yjnuw8U00tlvRtfKEKwImktpIgPE1R/bCd/k7CNQCvgpdm2YZn/fE7vSPBNSRFKLlE2nCJe5cmTywvgbzCfWWVTFk7ro1fY03dJke23CHPBw30GJFfyxfRbpOAAAA=="
  },
  "duet-01": {
    "slug": "duet-01",
    "alt": "Model in a charcoal dinner jacket with metallic swirl embroidery, hand in pocket.",
    "width": 3678,
    "height": 4905,
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoUABsAPt1YqE8opKOiMBgIARAbiWcAA+YBBdtsjQLoPfuQkLZhgAD+78NuksnLL/fuMMG5B1LT1PaFaMRHHNd4Yj+KPKzp44D8lah0G/fVmdezSxRhodxH0IJ+iWp9tmtGnln3djUcRVAEP0jemy4W1x9YKPMXsGpu+lg8cjf9hTSXEr0V0UNMKXE7ju1fhbphCAAA"
  },
  "duet-02": {
    "slug": "duet-02",
    "alt": "Back of a white pinstripe shirt embroidered with a tiger among blue clouds.",
    "width": 3196,
    "height": 4262,
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBACdASoUABsAPt1gp04opaOiMBgIARAbiWcAzuwPEFZO/ucVSo++ty2EgAD+8dexSiovmguffguXEfxeP2KJcsAKQD+iQadn8uBnM56V5Xj8xzGfPvdRZ2MDwMf2BBteb0cd39a2gnrjujG1aRbriMJr+tihSLN8mOYMNx++HFMAAAA="
  },
  "duet-03": {
    "slug": "duet-03",
    "alt": "Close view of a white pinstripe shirt with navy claw-mark embroidery.",
    "width": 2538,
    "height": 3385,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUABsAPt1irU6opaSiKAqpEBuJZwDE2AxroNGc/+UdqMAA/vHXDi8i3+MRkQGm7WVVFxkf9m3lhXounN9D2QY8cXEo557hZvd0F+GoZoMp2lIv7+zMZ1taJ6Fj0sAAAAA="
  },
  "pinstripe-01": {
    "slug": "pinstripe-01",
    "alt": "Model standing in a navy pinstripe wrap shirt, sash belt and wide trousers split at the hem with gold buttons.",
    "width": 3829,
    "height": 5105,
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBACdASoUABsAPt1iqE2opaOiMBgIARAbiWUAygAREfLLuzy2VSULTnlfOAAA/vHRtFVctiXqPZHPCYmDW5H7r3WS4gBzZHKlX9OIizi1dtEp3le1zVqPPKHpuI7B9PxLcXg9Rr1RM44cBw8Jg58lLZjm0xdTETI8Qf0BolleqvER2MDaAAAA"
  },
  "pinstripe-02": {
    "slug": "pinstripe-02",
    "alt": "Navy pinstripe wrap shirt with a wide sash belt and gold-buttoned cuffs.",
    "width": 3843,
    "height": 5124,
    "blur": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAABwBQCdASoUABsAPt1orFCopaQiqAgBEBuJQBWEF/wWgQtCWMknd1llznSOddEpkC6A9gYAAP7x4Ghi+ke/tsHHTLHrq79zVdvkzBMNhOy4htZ6q8Uv4D96uT/h7j0/V28PcHZspaB7a6I2vZ6UTDNY8V2bEWuwc4AW5gvDC0a+f3eYKGhKylE7d4cul/QhfhnHKFH28rUcz0IChcQiCMyMnuxWEVOa7oAckFeSwd7WHPzpV9/LPAw3JKaiVqUZ257YucNBcTk6h7FuaF7qwoeVC4hS20C03OZgfjAA"
  },
  "pinstripe-03": {
    "slug": "pinstripe-03",
    "alt": "Seated model in a navy pinstripe wrap shirt and split trouser with gold buttons.",
    "width": 4000,
    "height": 5333,
    "blur": "data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAABQBQCdASoUABsAPt1irE8opaSiKAqpEBuJQBdgP4EXKE5CMecPSxob6w8A2RIhIN0YkgAA/uKLTHnG9u9apq153Jud5j5jLD4pbzgcGadDZWH//XlKM/jeF5lP5ji58QmnO9AdM97iB/IN/30I4/B3tB22+F+vaxCXU5KaCG4GrrJe+1hAu9418DnHAfasTkYDKBuvS7nbns/7K0w1EFLy89oqhKc3tyfIRJhuAbOVCFjAD5NB6AI4zZVYatvV10aeMpVpS4hF77fgDc7dPPnj3HtyJEG+igoUEyjIAAA="
  },
  "pinstripe-04": {
    "slug": "pinstripe-04",
    "alt": "Model seated on a white chair in a navy pinstripe set, the trouser split open to the knee.",
    "width": 3863,
    "height": 5151,
    "blur": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAAAQBQCdASoUABsAPt1eqE2opSOiKA1REBuJQBibMYs5R71+0zzUX31zsACoXIDX/jPAAP7358snCkbSaFdhaarfXpRv8Jb1myqtpRlyNl/puUHkfGHE3jV7Gr0o3QgcITnEgxeQ4u5d3xKRRSUwDvikob/CET+vx9Xjqe7YZWPVkpxIJ0CAhM7/Ey+rm5getUcUU57JVy40W2QwQTBAXQpUiqGBmOijAT/wcw+W0DLOS4lPfVXyyzOKsChDPCV9/UAAAA=="
  },
  "pinstripe-detail": {
    "slug": "pinstripe-detail",
    "alt": "Gold buttons running up the split hem of a navy pinstripe trouser, the sash tie hanging beside it.",
    "width": 4000,
    "height": 6000,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoUAB4APt1ep0yopSOiMAgBEBuJQBZwAzoBUDd86qkc8ntatAAA/uyBRdsJSxd5CbjNs3WJ7MXFp8ZHoGnWhezN3OOYRyzAv2gukt/4phgmtAxXk/T6ft+SkLsfbNcxPY5/oaey1cGQktcq5ayT/x7q0U47Y0ZsrUM+yNyHG/BUeeM48aFPax0z9IhhKxQLOkBY75hQZ5gAnuNC/hgAAA=="
  },
  "swirl-shirt-01": {
    "slug": "swirl-shirt-01",
    "alt": "Model in a navy shirt with white swirl appliqué at the shoulder and hem, worn open with a pearl strand.",
    "width": 3901,
    "height": 5201,
    "blur": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAADwBACdASoUABsAPt1gqU4opaOiMBgIARAbiWUAxNssE5SGB3eDwVO3q5HhSaq3X2AA/vHPs4L9R9Vk/eBF0EgJa2RexECMKoQWSC6Pvz/JhDDEFWCfSI77+aLd6Cbsgay+oxT6o8CYHFYWL+ZP9YDAZLq40ZrBVM3Z6dUNLBGGxhuBwusZcZndP+jAbfMKEluYQpaIBdN5oWJ1DCIU/zjf3Qx8bhiX7mIOBS8i4M3kNcp7wdB46JM2y6ewX4JKnkAAAA=="
  },
  "swirl-shirt-02": {
    "slug": "swirl-shirt-02",
    "alt": "Navy shirt with raised white swirl appliqué at the collar and hem, worn over black trousers.",
    "width": 4000,
    "height": 5333,
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBACdASoUABsAPt1gqE4opaOiMBgIARAbiWcAzYQR8CuNpgsznhSoKy5QAP7x30p441l6aJlz3UpqFD4mv83ITNCadnoyB5ac3LnphMsfYBispz1w2RtUwiMyFja1PSLcRCvpgk2svAhGGtjW8Sub2po17u6TIFUGP+aya5Dsnrz7H7s8VebUMwu4Um81PO19K8oIyTP2BkCAwvUs8GWJx8AAAA=="
  },
  "swirl-shirt-detail": {
    "slug": "swirl-shirt-detail",
    "alt": "Close detail of white swirl appliqué and raw-edged cuffs on a navy shirt.",
    "width": 3261,
    "height": 4349,
    "blur": "data:image/webp;base64,UklGRvAAAABXRUJQVlA4IOQAAACQBQCdASoUABsAPt1ep0yopSOiMAgBEBuJQBajZfy1wkBk69T/aJXM+6wyVzH3bunWJDwK4AD+8F7Xs3lbZQOLlYsgje7da2EeUQRVGFcGU5+u1wJ3Z35DJxHXLQZn2Dk7d61s+kpiwZj5r16WwKRkZb9kFDb80qqrYqRDF7YjJHjgslDfuaRnvOqXw+aGh7EhBMGuLJnZUC1QPhet+LjkVebV+lnAi9L10Jh7cYTKo9WCQCNWAf+YqexjQtGGMPY2UNR4lvpnoN/KPwMsvmXyEL1p83m+NeenVENWNNn15HsAAAA="
  },
  "zip-jumpsuit-01": {
    "slug": "zip-jumpsuit-01",
    "alt": "Model in a sleeveless charcoal jumpsuit with a mandarin collar and an asymmetric zip.",
    "width": 4000,
    "height": 5333,
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBACdASoUABsAPt1ep0yopSOiMAgBEBuJZQDI1CFR7lpbIr9H9XgNuFfQAP7vw7ETgGkC1ffzQl6HAo7goXlg7h4LzrstyCLLdeNUGu1K9/tfBVltmepbZyYL+ZbczVn8I3kYDOu9DOoWvqaEwlrO6tUR1dMAESaPXrlnlAkb9ayNjI+Fco48U8yPW/fVCjGmqIZVyVqGQP6ZDMoeijvaNDP19EAA"
  },
  "zip-jumpsuit-02": {
    "slug": "zip-jumpsuit-02",
    "alt": "Charcoal jumpsuit with a silver zip curving from collar to hem.",
    "width": 3718,
    "height": 4958,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBQCdASoUABsAPt1mq1CopSOiqAgBEBuJYwDA3fwAXVIFJhj7G75gmthXmzFtzshNUwAA/u/XtJ/K1CsmYNYDTcMMu5CfEueFxXPKPRb0+8u0sE+u0ztESgYT5iq/Rs4CLoApuWEBe+6DbcUSWt5P7H90JGbf3Zzny5tkI79XnMt57SHSgwF4PZL87iODledsGXYmz0PG8oymkJNCkuoJ8XhAWLi0L+LvXMiCAAA="
  },
  "checker-shirt-detail": {
    "slug": "checker-shirt-detail",
    "alt": "Black shirt with a woven black-and-white checkerboard panel across the chest.",
    "width": 2817,
    "height": 3756,
    "blur": "data:image/webp;base64,UklGRjgBAABXRUJQVlA4ICwBAABwBwCdASoUABsAPt1kqE2opaOiMBgIARAbiWMArAHdI3lfRPsAc0B7Eoeq5YJhFHYB0418TRLLtB8xIOr2HmPnlmpkAAD+7jvO/FZUchCAXCBNHMvTqcCsBLsNU7wufEMNdzxkMlAwCKI1lfiiTJktKN++VpJRxVj1TNhJZ+XTG4mdBshLvVpzV9pI9835PbJaqcQD9myjMCsXXJPa74CIXNSwYK6dCYh8vWxYc3Y2Ed5eDK7tF2aMKrjz0PCT52PU5ToB7KPUE6sguUUhaDa3DclnAqoEACxqapi8JrZ5EEEd3YVIOyDLlOlEaZn+dge3Oup71Gk+kNRe69+2BMVHIfg1m8StMghNJEytE3y7629B7obLSh0TCypHmtw5kXTP5M3lx5vwNqHwAAA="
  },
  "pleated-trouser-crop": {
    "slug": "pleated-trouser-crop",
    "alt": "Black pleated trousers worn under an embroidered bandhgala.",
    "width": 1862,
    "height": 2234,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoUABgAPt1mrFEopSQiqAgBEBuJZwAAJuHWZxMvYxUtDdGTAAD+3gppRaK3t0cDF6Um4liAn/n4bZ3Te+/uxRl5x9fa3zztUuGxhniP1OWfLJ2xZTZPdzueX8PZyX+hIKxJJ0YMVcYtQq+FYkwK8EmOD9uo8aCzGwFa5i+UH2JsQe6rAfcuw+uXVoUeyrRI3uD0gWTgAAA="
  }
};

/** Full-size plate, 810w. */
export const photo = (slug: string) => `/img/campaign/${slug}-810.webp`;

/** Small plate, 400w — rail plates, grid cards, thumbnails. */
export const photoSm = (slug: string) => `/img/campaign/${slug}-400.webp`;

/**
 * srcset for anything that renders between the two.
 *
 * Paired with a `sizes` that states the rendered width, this lets a 300px rail
 * plate take the 400 and a full-bleed hero pane take the 810, rather than every
 * surface paying for the largest.
 */
export const photoSet = (slug: string) =>
  `${photoSm(slug)} 400w, ${photo(slug)} 810w` +
  ((PHOTOS[slug]?.width ?? 0) >= 1600 ? `, /img/campaign/${slug}-1600.webp 1600w` : "");

export const blurOf = (slug: string) => PHOTOS[slug]?.blur;

/**
 * The same two helpers, keyed by a catalogue `image` PATH rather than a slug.
 *
 * The catalogue stores paths, and half of it is still on generated SVG — which
 * needs neither a placeholder nor a second size, being a couple of KB and
 * resolution-independent. Both return undefined for anything that is not a
 * campaign plate, so a caller hands the result straight to `style` or
 * `srcSet` without branching.
 */
export const blurForImage = (src: string) => {
  const m = /\/img\/campaign\/(.+)-810\.webp$/.exec(src);
  const b = m && PHOTOS[m[1]]?.blur;
  return b ? `url("${b}")` : undefined;
};

/** True for a campaign photograph, false for a generated plate. */
export const isPhoto = (src: string) => src.startsWith("/img/campaign/");

export const setForImage = (src: string) => {
  const m = /\/img\/campaign\/(.+)-810\.webp$/.exec(src);
  return m ? photoSet(m[1]) : undefined;
};
