/**
 * GENERATED by scripts/photos.mjs — do not edit.
 *
 * One record per campaign frame: the intrinsic size (so every <img> can reserve
 * its box and the page never shifts), an alt string written against what is
 * actually in the picture, and a 20px blur placeholder to hold the space in
 * the right colours while the full plate decodes.
 */

export type Photo = {
  slug: string;
  alt: string;
  width: number;
  height: number;
  /** Inlined 20px WebP, scaled up under a blur until the real plate arrives. */
  blur: string;
};

export const PHOTOS: Record<string, Photo> = {
  "noir-vine-01": {
    "slug": "noir-vine-01",
    "alt": "Model in a black bandhgala with silver crystal vine embroidery across the shoulder and sleeve.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBQCdASoUABsAPt1kqU+opaOiKAqpEBuJZwAD5bkSoUSvl2Cly2zPGfSQdqnaMmC5wAD+3qRezDaskr8N4pHMe9s8v+BdVKbztRCDnC7kZZsKsmqDjRYXGprBWM20p/eEvsoGTCg8VduAU+feAfWXoRpWSbrettAA1BYENmiPmJOXHr4+a14i441qHZWqZ5mOBFX2twe7M6/2Nu7LZRgl4V2cfvmgAAA="
  },
  "noir-vine-02": {
    "slug": "noir-vine-02",
    "alt": "Close study of the crystal vine embroidery on the shoulder of a black bandhgala.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAwBQCdASoUABsAPt1kp1AopSMiqAqpEBuJZwDLpAzpsXmbNssLfKqxpxXGu/HUVh254AD+bEzAnorRuDS6aeX9T75LozyDDzEuLmR2N95dr/gbX/jMzxmJeXnnWMuvgniq6RsdarsJUUkb2wujPPYu8A37Qk4FhtRqWmhlbjnsAA0nIo/Tj+w5//T5apmBNDPiLKc5bCg6ZS3ru7LW/W5N95yEMRaDvAAAAA=="
  },
  "nocturne-gown-01": {
    "slug": "nocturne-gown-01",
    "alt": "Model in a black strapless column gown with a crystal-set bodice and peplum hem.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBACdASoUABsAPt1eqU4opSOjMBgIARAbiWcAAC2rCp5yQEtxvtHlh2YIAP7nM03ePUgCxGR72Y2j7dWTsaXT86u1Cy7aYv5DETnJWBTXvy8v2rJmgQy1PE2ZQ+0Absw/FeIXMXa4+hH0joObMuL2u24ud4ycrinhC8f/YugAAA=="
  },
  "nocturne-gown-02": {
    "slug": "nocturne-gown-02",
    "alt": "Black strapless gown with crystal beading at the bust and waist.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBQCdASoUABsAPt1cp0yopSOiMBgMARAbiWMAy2gPDTE7lI4DBZh5eEglzkqrZtyAAP7evzo6IfVQdOFGQsrxf4S71Ckn5npQ7cnQk/+WunG2PqtTsd+mSd3Vq2bh2tTDxQMhG+dU0ujK5gpD4iwYNuT/g/y27NJbtnE1M6EM4Tb2IngatieH5iF/IBqETLaXbauLJC8MlUYAAAA="
  },
  "nocturne-gown-03": {
    "slug": "nocturne-gown-03",
    "alt": "Full-length black column gown with a crystal peplum.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBQCdASoUABsAPt1YpkyopKOiMBgMARAbiWUAzf2MHHALgnIqvD4ZwmOD8vq0CuY1QAD+3oxdmagCuHF299foIRg4mIpny8vjvzxLrpYFeHcuYR+nZU9JUem13p9EH1HBZaWxv+OsZr16ha+hbnhmA/pH6TJMiurNrpbHrTrpiCtgtGdr535V0wRKWI1LTvmz1uIAgAA="
  },
  "nocturne-gown-04": {
    "slug": "nocturne-gown-04",
    "alt": "Detail of the crystal-set neckline on a black strapless gown.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAADwBQCdASoUABsAPt1kp1AopSMiqAqpEBuJYwCy7SAgxgwHul+pzbgY/MyQ7cQUhIZ5iulS2MY34AD+5zU2+qSyQpT19RzJZnxALsk0GO0wXNu+vDNhFRZbRLmSM8IJNQVQdmaNMCXocS5bJcDTpkcvWdMwNSYauIiiu0h4XGLi6/PBL8RgsJHeC+u5dgC2apXWxh1SPHnPPpFRrOZP7frsh7la2uz8QV3zS3BAqRnPflQ0+GzZ0nl+Fk4jJwAA"
  },
  "silver-seam-01": {
    "slug": "silver-seam-01",
    "alt": "Model in a black shawl-collar dinner jacket with crystal-encrusted front panels.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwAwCdASoUABsAPt1eo0yopSMiMBgMARAbiWcAACEgBI4SfBbODkZAAP7nQMLyW/sMf/waotteSDDeK7I6TZEyfUYszGZI9pxUWOYXVKXvUYd9UvPMOXg8Dq6BNYXpDrzBm/rPf5L8kefgwxVdY9n1fiXV+DSxzkqNSAS7sik1qb3C9TKpQR9JhJt5wIAA"
  },
  "silver-seam-02": {
    "slug": "silver-seam-02",
    "alt": "Black dinner jacket with silver crystal panelling, worn open over a pintucked shirt.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAABwBQCdASoUABsAPt1kqk+opaOiKAqpEBuJZwAML+B41oipBDSLRJcD0yPxyEBLqRHSfggAAP7qeGAhn5JUXzsYMAYPkADTYI76IoD8W9KVnrvpL4S6DUpB1h3W5Cz3w3yFtYIF7O0wPmtDek4lzgB0LGODAGE4i1Wissp1FsiDoUNKIp48FEluQm2ZwXBNJVq372DndbbbuKuCgey1kuAfDgTCzz2UT69CvYobtNUFUSFyZZgoAA=="
  },
  "silver-seam-detail": {
    "slug": "silver-seam-detail",
    "alt": "Close detail of hand-set crystal panelling on a black shawl-collar dinner jacket.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAABwBQCdASoUABsAPt1kqU+opaOiKAqpEBuJZwDIXBIoie3a1Teuli9D9Htnw1aRc9hv3cmAAP7tzxuu+N6j7BBiLWx+P5D9qfUpCN+fwNnoxvuLVQAZAqVX7n7L5sKWC7N81NLaLLhNiqRrH+5BBg78zpXnoJEhe2IZPQnQO5VkMiwhsf+OAo6ElG6GyUYhQXif2TzzGvK/B5yPu1kuWEnHpyqxzIVWMT51ORg5PdgbUjhGYDmdPNPY1UjHtqFxvuO0LjUAAAA="
  },
  "orbit-01": {
    "slug": "orbit-01",
    "alt": "Model in a black bandhgala scattered with embroidered circles in navy and crystal.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoUABsAPt1iqk8opaOzqAqqcBuJZQAAH4mXrzPWX0n2iJ1foQAA/uqV6Dpr+5i47fSuVmXZCXU7XpUFWbguuMb51r7ghXiGOQSaHrPm/JFjpOaNfv7fJDdWnOwj0A9jlbZsH57wOjE8wL8NqgGDvEzzI2fGsWSZYEZxu5PF/iqChLgAAAA="
  },
  "orbit-02": {
    "slug": "orbit-02",
    "alt": "Black bandhgala with circular embroidery across the chest and sleeve.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoUABsAPt1cp0yopSOiMBgMARAbiWcAAC62lW05icQIDt7LueUAAP7qelnp3PNAyWMR0R5TJYElQyykDlyf85N5TkCYCg4JDPrXfdpLhduPHwwPgvTuemQo3/CGnlndZRni0HDHOKDi3KNSR/aZPtvuG6MMOpat1lJAMDVrmRD9KJtXigAAAA=="
  },
  "orbit-03": {
    "slug": "orbit-03",
    "alt": "Seated model in a black circle-embroidered bandhgala.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAABQBgCdASoUABsAPt1cqU6opKOiMBgIARAbiWcAy6Xdy35jPKZjez0BBxAfuFpwnZOY1cVD+DbHtacAwAD+5+4fU5CCH9rRfdxZz7pqTg5ZINQXqHLKlAzvTbGcRuyTCgESHE1KdEH1PBtYlzNxqPZQPo/ONZeVy1WE9jySfz2H0J+p0HrqbvRtiRy60G+9ovaGvuKKJFPxuzxeaq6H+/4YRnJuFhLuH9OpYdCpxWqoPb7tbaetLfmk5fetgGY4ItxsIrln85H+VXFLDq6MRGEfqH+3zMAA"
  },
  "vapour-gown-01": {
    "slug": "vapour-gown-01",
    "alt": "Model in a lilac satin slip gown with a sequinned hem.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUABsAPt1ep0yopSOiMAgBEBuJZwDM0CFQM4DZH0/kGKwrgAD+6nq2ZFSQg99cdtAYIPYfT33+26+rdbYgk+CVa6ngvZ0ybot0anHTciT2kYLw0+IEeEbn7d2lPm5v4IAAAA=="
  },
  "vapour-gown-detail": {
    "slug": "vapour-gown-detail",
    "alt": "Detail of graduated sequin work on the bodice of a lilac satin gown.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACwBQCdASoUABsAPt1aqU8opKOiMBgIARAbiWMAuyEgAXBuhC57ioWZXZGzQnnZP3TWDpLSkHAA/ucle3JbcaBhRWYW6dVlLxOKsXSLZsrYIZD4Mpjq4FHaDxSENQfBPLKzCF99xSvIyUBEycKSky1DJjS4RMFrd7YY3AxiEnBRqQkaSba6VHxN41JN2Q8gBFU19ud9h7rP0M9GzTHhFRY2Nu9DewQ3M+EJH0ERIvP0aoD/Zln5TYWMAAA="
  },
  "midnight-swirl-01": {
    "slug": "midnight-swirl-01",
    "alt": "Model in a navy dinner jacket with crystal swirl embroidery on the shoulders.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoUABsAPt1iqk+opSOjKAqpEBuJZQAALrqCbmn4ZJ2QLfKq0AD+6nhfnDzJJ0YCmf6e9Px/tv/XRGVBKcZmkxDZCsFA+U1DNj8hQl4n7ETKJPqPziv1+/0HYvsQZFEF5lK34V0E/MZFI4nV3BeRDr3GF4F+tSE4l3KrA4LOGEZH6BJLWi0iAAAA"
  },
  "midnight-swirl-detail": {
    "slug": "midnight-swirl-detail",
    "alt": "Close detail of crystal swirl embroidery on a navy dinner jacket.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAACwBQCdASoUABsAPt1kqU+opaOiKAqpEBuJYwDA3A34vs+dqTci/+3WNJcG+MagBUMs6GgIcUgA/uqWuaLo0F5okEKbMo5KJkBLB5lXLNmK7o0upcVdkm9oyPjdaZMw/mUdVw2Os2cQ00ncJgtB9COqBwKUj6ABEpNxB2Mmi7s0CQvDQq5V58uQIL1c63OZZgmf8qN2+XHqQvx8udVdyWgqcX81aKZ+4lt2Y/byUUbC7l+qfjp2FFWgc8/mb4UGxxNmKc/dPWg8GfQVn8rV5z0Q3rnrysq45gAAAA=="
  },
  "tidemark-detail": {
    "slug": "tidemark-detail",
    "alt": "Scalloped metallic embroidery along the hem and cuff of a long navy sherwani.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBACdASoUABsAPt1apUyopSOiMAgBEBuJZwC7ACPgdGbK6GQIWlHt25iwP4NQ8oAA/up/l0cWfGASGJQBQ+Jir+/KbA6h7G1kXGh8LzEZW+yd896KTeb+SPvIKCDac36kpMZZNn0y/JjM9ls8WAHx9bUwiFKKwfbbB+a1QJDPy8Nck/l0oOImGLfVoGu6ax1sO+u5WiEd24xwmNxZ3zNPhBecR0HvVMgAAA=="
  },
  "duet-01": {
    "slug": "duet-01",
    "alt": "A couple in black eveningwear — an embroidered bandhgala and a crystal-set gown.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRuAAAABXRUJQVlA4INQAAACwBQCdASoUABsAPt1mq1CopSOiqAgBEBuJZQDImAyO74Y6A3ZeySLA82L2W/VckDUHAEhKkOAA/ug6s25xVDRPRAqbHyb68BtM4KB3jCRb+io43RP3uLLiqUZujN2f/WnOywQx5qB0XKy3dNV0Bt7rzEaCOvwz8O6heMjDFxEfALyoyK2fuT9xV+3ZAH+D/d4wb3sxFlxgWP8a2xGN3LttoDc9kcvi5gNwy7ZolsiAy1oWttMuAgFzUZ4YF0vJF9ySCcw6DjaUDwGFlFptKnS9AEAAAA=="
  },
  "duet-02": {
    "slug": "duet-02",
    "alt": "A couple — a man seated in a circle-embroidered bandhgala, a woman standing in a lilac satin gown.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAACwBQCdASoUABsAPt1cpkyopSOiMBgMARAbiWMAA+XpBdH3GTXX5OfqZXmazHnw29I/ZgCdAEAA/ucZHCDbuF6IlxgPtdlxZo+Hnado5RkVXAV/7s2DxN4wiWCdeh5aFWwhr9EAn5JtNU4V40fv8pIlYCzQuIESKssQDSsHUJUAIdlAOrbDv9ngKSwyZV+5rqxjDLx5/8xZWfFgveyI+7o2G4PYPmszmduRE2XjFie2OO8ENy+sEEGPy4psfOp9S1qkqFgAAAA="
  },
  "duet-03": {
    "slug": "duet-03",
    "alt": "A seated man in an embroidered bandhgala with a woman in a lilac satin gown behind him.",
    "width": 810,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBQCdASoUABsAPt1cok0opSMiMBgMARAbiWcABRKBaXF2F45xPc6d4+DIeBIea98AAP7qepfGKCym2/OK5YKgfRs6rUG+0+sbbx8OZIACfhaGacZz7uTVYbgOnDbhPndQmHRA8V+4lps/8OnUh3yKuHDW9/sPk0qupdP0b/iGYRig3VjD4JthiOtLS2Bu4VS8VQ66iTkXnr+p4yTcIKfAAAA="
  },
  "pleated-trouser-crop": {
    "slug": "pleated-trouser-crop",
    "alt": "Black pleated trousers worn under an embroidered bandhgala.",
    "width": 365,
    "height": 486,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQBACdASoUABsAPs1WokynpSMiN/qoAPAZiWkAAEqGu5OvFfTe3C8HnLYAAP7gcDa4molFwVHgzQLCYt+TXmioaCljBBeup0cvAMBh9rKoy5TAnLMDroOoHsSTbNbAAAA="
  }
};

/** Full-size plate, 810w. */
export const photo = (slug: string) => `/img/campaign/${slug}-810.webp`;

/** Small plate, 400w — rail plates, grid cards, thumbnails. */
export const photoSm = (slug: string) => `/img/campaign/${slug}-400.webp`;

/**
 * srcset for anything that renders between the two.
 *
 * Paired with a `sizes` that states the rendered width, this lets a 300px rail
 * plate take the 400 and a full-bleed hero pane take the 810, rather than every
 * surface paying for the largest.
 */
export const photoSet = (slug: string) =>
  `${photoSm(slug)} 400w, ${photo(slug)} 810w`;

export const blurOf = (slug: string) => PHOTOS[slug]?.blur;

/**
 * The same two helpers, keyed by a catalogue `image` PATH rather than a slug.
 *
 * The catalogue stores paths, and half of it is still on generated SVG — which
 * needs neither a placeholder nor a second size, being a couple of KB and
 * resolution-independent. Both return undefined for anything that is not a
 * campaign plate, so a caller hands the result straight to `style` or
 * `srcSet` without branching.
 */
export const blurForImage = (src: string) => {
  const m = /\/img\/campaign\/(.+)-810\.webp$/.exec(src);
  const b = m && PHOTOS[m[1]]?.blur;
  return b ? `url("${b}")` : undefined;
};

export const setForImage = (src: string) =>
  src.endsWith("-810.webp")
    ? `${src.replace("-810.webp", "-400.webp")} 400w, ${src} 810w`
    : undefined;
